baseURL = "https://stephane-panda.github.io/Stephane-Bonda-Belo/"
languageCode = "fr-fr"
paginate = 6
theme = "yro"
title = "Stéphane Bonda Belo"
# Main Menu
[[menu.main]]
name = "Acceuil"
url = "#home"
weight = 1
[[menu.main]]
name = "compétences"
url = "#service"
weight = 3
[[menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Cv"
url = "#resume"
weight = 5
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 2
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 9

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Stephane bonda belo 2020"
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Vevey, 1800"
email = "stephane.bondabelo@heig-vd.ch"
phone = "+41 78 921 7384"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-instagram-square"
url = "https://www.instagram.com/"
weight = 3


[taxonomies]
  category = "categories"
  tag = "tags"